load("@tf//build_defs:fsl_library.bzl", "fsl_library")

cxx_binary(
    name = "03_MultiThread",
    srcs = ["03_MultiThread.cpp"],
    link_style = "static",
    deps = [
        "@tf//:TF",
    ],
    visibility = ['PUBLIC']
)

fsl_library(
    name = "fsl",
    srcs = ["Shaders/FSL/ShaderList.fsl", "@tf//:UI_ShaderList", "@tf//:Font_ShaderList"],
    visibility = ['PUBLIC']
)

export_file(
    name = "gpu.cfg",
    mode = "reference",
    src = "gpu.cfg",
    visibility = ['PUBLIC']
)


